notifications:
webhooks:
  urls:
    - https://webhooks.gitter.im/e/2570c8e12e6b4bbafb53
  on_success: always
  on_failure: always
  on_start: always

language: node_js
node_js:
   - "4.4.5"
sudo: false

branches:
  only:
    - master

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - cd petabencana-aurelia

install:
  - npm install
  - npm install aurelia-cli -g

script:
  - au build
